### PR TITLE
Support for custom slot types using curly braces while retaining backward compatibility

### PR DESCRIPTION
**Pull request by rickwargo**
Modified previous approach to have it be backwards compatible and support parens for grouping and alternation and curly braces for custom slot names.

Modified tests where appropriate to use parens for grouping.
Added additional tests to use curly braces for grouping.
Added test for new approach custom slot type.

Also supports use of {-|Name} and {Name} for custom slots.

Note: does not support nested groups - will open issue and work on pull request for that.

### CODE REVIEW

**Comment by rickwargo** [comment]
There is a deprecated message in the code (commented out) for using curly braces for grouping in alternation. Feel free to uncomment if you want the message.

**Comment by mreinstein** [comment]
sounds good. Do the examples need updating? They appear to still reference `{ }` syntax.

**Comment by rickwargo** [comment]
Yes - I can get that, too. Thanks for the hint :)

**Comment by rickwargo** [comment]
@mreinstein what to do documentation-wise in the examples that reference the deprecated LITERAL approach - e.g. {red|green|blue|NAME}? 

Should I remove them and put in more recent examples? Or leave them as is? Or switch over to parens? Personally I don't like the parens in this approach.

This PR continues to support that with either curly braces or parens.

**Comment by mreinstein** [comment]
hmm, I dunno. My plan was to just remove the old syntax (the new one that was added to 0.2 and just go with parens.) Because there are a bunch of other breaking changes in 1.x. 

Perhaps I'll give this more thought before proceeding.

**Comment by rickwargo** [comment]
Think I made it more difficult for you by support the old syntax and the new syntax simultaneously. I can also yank support for the old syntax if you prefer.

**Pull request merged**
